### ISSUE TITLE
Schema support for sql server

### ISSUE THREAD

**Issue by aperotte** [OHDSI/FeatureExtraction#1]
I'm running into an issue where I cannot run cohort method on sql server where my ohdsi instance and vocabulary exist in a schema that is _not_ dbo.  I have tracked down the issue to two places:

1) getCovariates.sql may need to prefix the table names with @cdm_database in order to fully support schemas on sql server.  The "USE" statement at the beginning of the script only puts the database in scope, not the schema.

2) Line 43 in GetDefaultCovariates.R splits the database name on periods and therefore removes the schema name.  The particular line of code is on line 43 and states:

cdmDatabase <- strsplit(cdmDatabaseSchema, "\.")[[1]][1]

The database name without the schema name is then passed on to sqlrender.  Therefore, changing getCovariates.sql may not be enough to fully support schemas on sql server.

**Comment by schuemie** [comment]
Thanks for bringing this up. I'm away this week. Will fix this next week.

**Comment by aperotte** [comment]
Thanks! I can try to create a pull request if you'd like.

**Comment by schuemie** [comment]
Yes, please do!
