### ISSUE TITLE
Move FeatureExtraction to CRAN

### ISSUE THREAD

**Issue by schuemie** [OHDSI/FeatureExtraction#104]
Eunomia has now [made it to CRAN](https://cran.r-project.org/web/packages/Eunomia/index.html), and we can start using it in examples in our CDM-facing packages such as FeatureExtracion. We should aim to have FeatureExtraction in CRAN next, as pretty much everything else depends on FeatureExtraction.

The first step would be to make sure every FeatureExtraction function has a runnable example.

**Comment by ginberg** [comment]
Eunomia 2.0 is on CRAN, so we can move forward with this:-)

**Comment by ginberg** [comment]
FYI I have made a first attempt to submit to CRAN using the [cran](https://github.com/OHDSI/FeatureExtraction/tree/cran) branch. It's passing all automated checks but there are some comments from manual inspection, see below.

> Please do not start the description with "This package", package name,
> title or similar.
> 
> Please provide a link to the used webservices to the description field
> of your DESCRIPTION file in the form
> <http:...> or <[https:...](https://github.com/OHDSI/FeatureExtraction/issues/...)>
> with angle brackets for auto-linking and no space after 'http:' and
> 'https:'. -> Common Data Model
> 
> The Description field is intended to be a (one paragraph) description of
> what the package does and why it may be useful. Please add more details
> about the package functionality and implemented methods in your
> Description text.
> 
> If there are references describing the methods in your package, please
> add these in the description field of your DESCRIPTION file in the form
> authors (year) <doi:...>
> authors (year) <arXiv:...>
> authors (year, ISBN:...)
> or if those are not available: <[https:...](https://github.com/OHDSI/FeatureExtraction/issues/...)>
> with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
> auto-linking. (If you want to add a title as well please put it in
> quotes: "Title")
> 
> Please add \value to .Rd files regarding exported methods and explain
> the functions results in the documentation. Please write about the
> structure of the output (class) and also what the output means. (If a
> function does not return a value, please document that too, e.g.
> \value{No return value, called for side effects} or similar)
> 
>      -> Missing Rd-tags:
>       saveCovariateData.Rd: \value
>       tidyCovariateData.Rd: \value
> 
> "Using foo:::f instead of foo::f allows access to unexported objects.
> This is generally not recommended, as the semantics of unexported
> objects may be changed by the package author in routine maintenance."
> 
> Please omit one colon.
> 
> -> Warning: Used ::: in documentation:
>       man/aggregateCovariates.Rd:
>          covariateData <-
> FeatureExtraction:::createEmptyCovariateData(cohortIds = 1, aggregated =
> FALSE, temporal = FALSE)
>       man/createEmptyCovariateData.Rd:
>          covariateData <-
> FeatureExtraction:::createEmptyCovariateData(cohortIds = 1, aggregated =
> FALSE, temporal = FALSE)
>       man/filterByCohortDefinitionId.Rd:
>          covariateData <-
> FeatureExtraction:::createEmptyCovariateData(cohortIds = 1, aggregated =
> FALSE, temporal = FALSE)
>       man/filterByRowId.Rd:
>          covariateData <-
> FeatureExtraction:::createEmptyCovariateData(cohortIds = 1, aggregated =
> FALSE, temporal = FALSE)
>       man/isAggregatedCovariateData.Rd:
>          covariateData <-
> FeatureExtraction:::createEmptyCovariateData(cohortIds = 1, aggregated =
> FALSE, temporal = FALSE)
>       man/isTemporalCovariateData.Rd:
>          covariateData <-
> FeatureExtraction:::createEmptyCovariateData(cohortIds = 1, aggregated =
> FALSE, temporal = FALSE)
>       man/saveCovariat [... truncated]
> 
> You have examples for unexported functions. Please either omit these
> examples or export these functions.
> 
> -> Examples for unexported function
>    createTemporalCovariateSettings() in:
>       dot-createLooCovariateSettings.Rd
>       dot-getDbLooCovariateData.Rd
>    createTemporalSequenceCovariateSettings() in:
>       dot-getDbLooCovariateData.Rd
> 
> \dontrun{} should only be used if the example really cannot be executed
> (e.g. because of missing additional software, missing API keys, ...) by
> the user. That's why wrapping examples in \dontrun{} adds the comment
> ("# Not run:") as a warning for the user. Does not seem necessary.
> Please replace \dontrun with \donttest.
> 
> Please unwrap the examples if they are executable in < 5 sec, or replace
> dontrun{} with \donttest{}.
> 
> Please always make sure to reset to user's options() after you changed
> it in examples and vignettes and demos.
> e.g.:
> 
> old <- options(digits = 3)
> ...
> options(old)
> 
>   ->  inst/doc/UsingFeatureExtraction.R,
> inst/doc/UsingFeatureExtractionKorean.R
> 
> Please always add all authors, contributors and copyright holders in the
> Authors@R field with the appropriate roles.
>  From CRAN policies you agreed to:
> "The ownership of copyright and intellectual property rights of all
> components of the package must be clear and unambiguous (including from
> the authors specification in the DESCRIPTION file). Where code is copied
> (or derived) from the work of others (including from R itself), care
> must be taken that any copyright/license statements are preserved and
> authorship is not misrepresented.
> Preferably, an ‘Authors@R’ would be used with ‘ctb’ roles for the
> authors of such code. Alternatively, the ‘Author’ field should list
> these authors as contributors. Where copyrights are held by an entity
> other than the package authors, this should preferably be indicated via
> ‘cph’ roles in the ‘Authors@R’ field, or using a ‘Copyright’ field (if
> necessary referring to an inst/COPYRIGHTS file)." e.g.: Observational
> Health Data Sciences and Informatics in ReadCSVFileWithHeader.java
> Please explain in the submission comments what you did about this issue.
> 
> Please fix and resubmit.

**Comment by ginberg** [comment]
FeatureExtraction is now on [CRAN](https://cran.r-project.org/web/packages/FeatureExtraction/index.html)!
