### ISSUE TITLE
CCI score included concepts

### ISSUE THREAD

**Issue by sfortin1** [OHDSI/FeatureExtraction#108]
The following concept used to define "Diabetes with chronic calculation" within the calculation of the CCI score seems strange from a clinical standpoint:

-  4192279; Medical Research Council Dyspnoea scale grade 5

Code in question can be found here: https://github.com/OHDSI/FeatureExtraction/blob/master/inst/sql/sql_server/CharlsonIndex.sql

**Comment by anthonysena** [comment]
Thanks @sfortin1! Agreed that concept does look a bit odd. Looking in the vocabulary for that concept, it is pretty isolated (meaning it does not have any descendants besides itself). I'm not sure if there is a replacement concept that should be used in place of this one...but I think removing this one makes sense.
