### ISSUE TITLE
Switch from oracleTempSchema to tempEmulationSchema

### ISSUE THREAD

**Issue by schuemie** [OHDSI/FeatureExtraction#126]
The newer versions of SqlRender and DatabaseConnector have deprecated oracleTempSchema in favor of tempEmulationSchema. Not only is this is rename of the same argument, it now also defaults (in all public function interfaces) to `getOption("sqlRenderTempEmulationSchema")`. The goal eventually is to no longer require perpetuating this argument through the code but rely on the global option instead.

For FeatureExtraction this means `oracleTempSchema` needs to be deprecated, and `tempEmulationSchema` needs to be added to various functions. See [this commit in MethodEvaluation](https://github.com/OHDSI/MethodEvaluation/commit/d69765fd52ab695f8b5fb89db0663f10b30480f1) for examples of the changes that are required.

**Comment by schuemie** [comment]
After a grace period of 4 years, oracleTempSchema is about to be completely removed. Please make sure FeatureExtraction switches to tempEmulationSchema at the nearest opportunity. See https://github.com/OHDSI/DatabaseConnector/issues/289

**Comment by anthonysena** [comment]
Moving this to the v3.7.0 milestone since the addition of the `tempEmulationSchema` maintains backwards compatibility. We'll then use #159 to remove the `oracleTempSchema` in the v4.0 release.
