### ISSUE TITLE
Using different endDays for different standard covariate sets

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/FeatureExtraction#139]
There is only a single parameter `endDays`, which is used as the end date for all covariates, even the one that are any time prior. Here is the code: [Link](https://github.com/OHDSI/FeatureExtraction/blob/7e615050508bd1915e8437cf98fceacacbda4b9c/R/DefaultCovariateSettings.R#L602)

I would like to have `endDays = 0` for covariates that are assessed any time prior, but `endDays = -4` for covariates that are assessed for a long term window.

Is this possible (maybe with a small hack)?

**Comment by jreps** [comment]
A hack you can currently do is to create two covariate settings, one with any time prior covariates and end days = 0 and another with long term covariates and end days = -4, then combine these by creating a list of these settings: allCovs <-  list(covAnyTime, covLongterm).

**Comment by lhjohn** [comment]
Does this also work with `SkeletonPredictionStudy`, because when using the code below, the package wont get past creating the covariate tables?

Or should I better edit this directly in the hydrated package?
```
covariateSettings <- list(list(list(fnct = 'createCovariateSettings',
                                    settings = list(FeatureExtraction::createCovariateSettings(useDemographicsGender = T,
                                                                                               longTermStartDays = -183,
                                                                                               endDays = -4,
                                                                                               useDrugGroupEraLongTerm = T),
                                                    FeatureExtraction::createCovariateSettings(useConditionGroupEraAnyTimePrior = T,
                                                                                               endDays = 0)))
)
```

**Comment by lhjohn** [comment]
Ok, now that I think about it, I can probably just do this?
```
covariateSettings <- list(list(list(fnct = 'createCovariateSettings',
                                                       settings = FeatureExtraction::createCovariateSettings(useDemographicsGender = T,
                                                                                               longTermStartDays = -183,
                                                                                               endDays = -4,
                                                                                               useDrugGroupEraLongTerm = T)),
                               list(fnct = 'createCovariateSettings',
                                                       settings = FeatureExtraction::createCovariateSettings(useConditionGroupEraAnyTimePrior = T,
                                                                                               endDays = 0))
)
```

**Comment by jreps** [comment]
# in general this should work:
covariateSettings <- list(FeatureExtraction::createCovariateSettings(useDemographicsGender = T,
                                                            longTermStartDays = -183,
                                                            endDays = -4,
                                                            useDrugGroupEraLongTerm = T),

FeatureExtraction::createCovariateSettings(useConditionGroupEraAnyTimePrior = T,
                                                                                               endDays = 0)
)

but if you want to edit the prediction json then try something like this should work:
list(
list(fnct = 'createCovariateSettings',
            settings = FeatureExtraction::createCovariateSettings(useDemographicsGender = T,
                                                            longTermStartDays = -183,
                                                            endDays = -4,
                                                            useDrugGroupEraLongTerm = T)
),

list(fnct = 'createCovariateSettings',
      settings = FeatureExtraction::createCovariateSettings(useConditionGroupEraAnyTimePrior = T,
                                                                                               endDays = 0)
)
)

**Comment by lhjohn** [comment]
Thank you @jreps, those worked.
