### ISSUE TITLE
Faulty SQL fires from CohortDiagnostics - CohortCharacterizationDiagnostics.R & TABLE condition_era

### ISSUE THREAD

**Issue by lofung** [OHDSI/FeatureExtraction#140]
Hello, we are still running the Cervello Study of OHDSI. We are down to the last part and an error came out.

When running CohortDiagnostics, the script came to an error here.

````
....

Running Cohort Overlap took 1.47 secs
Characterizing cohorts
Starting large scale characterization of 1 cohort(s)
Constructing features on server
  |==                                                                    |   2%
  
  Error: Error executing SQL:
org.postgresql.util.PSQLException: ERROR: column "condition_era_start_date" does not exist
  Position: 501
An error report has been created at  C:/Users/user_le_me/errorReportSql.txt
Run `rlang::last_error()` to see where the error occurred.


````

I have located that it seems it calls a function on line ````1068```` in https://github.com/OHDSI/CohortDiagnostics/blob/master/R/RunDiagnostics.R

That it leads to 

https://github.com/OHDSI/CohortDiagnostics/blob/master/R/CohortCharacterizationDiagnostics.R

````featureExtractionOutput <-  FeatureExtraction....````

The SQL that fires is as follows

````

CREATE TEMP TABLE cov_1

AS
SELECT
CAST(ancestor_concept_id AS BIGINT) * 1000 + 212 AS covariate_id,
	

	cohort_definition_id,
	COUNT(*) AS sum_value


FROM
(
	SELECT DISTINCT ancestor_concept_id,
	

		cohort_definition_id,
		cohort.subject_id,
		cohort.cohort_start_date
	
	FROM ohdsi_cerevello_output.cervello_output cohort
	INNER JOIN ohdsiv5_june2021_thin.condition_era
		ON cohort.subject_id = condition_era.person_id
	INNER JOIN groups
		ON condition_concept_id = descendant_concept_id

	WHERE condition_era_start_date <= (cohort.cohort_start_date + 0*INTERVAL'1 day')
				AND condition_era_end_date >= (cohort.cohort_start_date + -30*INTERVAL'1 day')
		AND condition_concept_id != 0



		AND cohort.cohort_definition_id IN (3042)
) temp
		
GROUP BY cohort_definition_id,
	ancestor_concept_id
	
````

I have immiedately found a few errors here

(1) ````ohdsiv5_june2021_thin```` is a correct schema. However, ````condition_era```` is a table that is no longer used https://www.ohdsi.org/web/wiki/doku.php?id=documentation:cdm:condition_era

(2) At the second ````INNER JOIN````. I have no idea where ````groups```` show up. There weren't any table named ````groups```` that was mentioned previously (perhaps it was a temp table I can never get tracked)

(3) ````condition_era_start_date```` and ````condition_era_end_date```` seems like columns used in ````condition_era````, which now should be on a newer table and newer column?

Unfortunately, at this rate, the script is just too convoluted I cannot point out which SQL script is wrong in the repository lol

**Comment by lofung** [comment]
Turns out it should be the CDM create table scripts that should be at fault?

**Comment by anthonysena** [comment]
Hi @lofung. Are you using CDM v5.3.1? Per https://ohdsi.github.io/CommonDataModel/cdm531.html#CONDITION_ERA, `condition_era_start_date` and `condition_era_end_date` are part of the table specification.

**Comment by anthonysena** [comment]
Closing since `condition_era_start_date` and `condition_era_end_date` are part of the table specification.
