### ISSUE TITLE
CONDITION_TYPE_CONCEPT_IDs used to define inpatient diagnoses are no longer valid

### ISSUE THREAD

**Issue by schuemie** [OHDSI/FeatureExtraction#141]
Currently FeatureExtraction [uses the `CONDITION_TYPE_CONCEPT_ID` field to identify inpatient diagnoses](https://github.com/OHDSI/FeatureExtraction/blob/master/inst/sql/sql_server/DomainConcept.sql#L40). However, these are no longer valid. I think moving forward we will need the link the `VISIT` table to establish whether conditions are inpatient?

**Comment by schuemie** [comment]
Alternatively, we could check whether the condition occurrence overlaps in time with an inpatient visit (rather than rely on a direct link between the two)?

**Comment by cukarthik** [comment]
I think that might be better option since not all conditions might have a link to a visit due to data streams, at least in the US (ie pathology and radiology physician billing codes are at times disconnected from the hospital account because the physicians are a different entity from the hospital).

**Comment by anthonysena** [comment]
I'm planning to implement this by looking for the domain event (i.e. condition_occurrence) that occurs during an inpatient visit. To that end, I'm going to use the vocabulary to look at the `visit_occurrence` table for all `visit_concept_id`s that are descendants of concept_id == 9201 (https://athena.ohdsi.org/search-terms/terms/9201).
