### ISSUE TITLE
[BUG] Duplication of analysis id's - PrespecTemporalAnalyses

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/FeatureExtraction#144]
**Observed:**
![image](https://user-images.githubusercontent.com/13936600/139724699-d8608e0e-f374-42df-97c5-6c2f0e434b16.png)

https://github.com/OHDSI/FeatureExtraction/blob/master/inst/csv/PrespecTemporalAnalyses.csv#L22

and

https://github.com/OHDSI/FeatureExtraction/blob/master/inst/csv/PrespecTemporalAnalyses.csv#L23

**Expected:**
Should be different id's

Causes duplication in results

![image](https://user-images.githubusercontent.com/13936600/139724828-bde3c34a-fb69-4821-ba29-e8d8d8a412a0.png)

**Comment by gowthamrao** [comment]
![image](https://user-images.githubusercontent.com/13936600/139726080-7df3f20b-d8ac-42ba-8bfb-131baa58345a.png)

**Comment by gowthamrao** [comment]
I wonder if this is true 

In Atlas - if i choose the following covariate settings for estimation module, am i clashing two analysis ids?



![image_2022_08_19T12_23_12_494Z](https://user-images.githubusercontent.com/13936600/185618780-24a44efe-6076-497c-bd27-6abb74cdbc26.png)

drug_era short/long - drug era start -- 401
drug_era_group long/short -- 403

drug_era_group_overlap -- 403  ----- duplicate
drug_exposure short/long -- 301

**Comment by gowthamrao** [comment]
I do not know if Cohort Method is using PreSpecTemporalAnalyses or temporalAnalyses

**Comment by anthonysena** [comment]
@ginberg as discussed, let's clean up the comments here:

https://github.com/OHDSI/FeatureExtraction/blob/5363f5f4cdaf8b31ce9f193861169047b11ea41c/R/DefaultTemporalCovariateSettings.R#L65-L70
