### ISSUE TITLE
Can't find where #time_period is created

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/FeatureExtraction#150]
I don't know if this is an issue, but looking through the DomainConceptGroup.sql file there is a reference to the [temp table time_period](https://github.com/OHDSI/FeatureExtraction/blob/bddb9ca9ce946a540b04e7bfa0a2465344b7b249/inst/sql/sql_server/DomainConceptGroup.sql#L115); however, I don't see where it's created.

**Comment by anthonysena** [comment]
Hi @cukarthik - this temp table is created via Java: https://github.com/OHDSI/FeatureExtraction/blob/master/java/org/ohdsi/featureExtraction/FeatureExtraction.java#L562. It will take the info from the `covariateSettings` and create that temp table before executing analyses such as the DomainConceptGroup.sql.

I'll close this but feel free to re-open if you have additional questions.

**Comment by cukarthik** [comment]
Thanks!
