### ISSUE TITLE
Add covariates based on care_site_id

### ISSUE THREAD

**Issue by schuemie** [OHDSI/FeatureExtraction#164]
Although probably not enabled by default, it would be good to allow creating covariates based on the `care_site_id`. These would be binary covariates, one per unique `care_site_id`. Probably the covariate ID can be `care_site_id * 1000 + analysis_id`. 

The `care_site_id` is a field of the `person`, `visit_occurrence`, and `visit_detail` tables. I guess ideally we'd want to try to get the `care_site_id` in the reverse order of those tables, so first see if there's a `visit_detail` record spanning the index date with a `care_site_id`, and if not, check `visit_occurrence` and then `person`.

This analysis could be added to the [prespecified analyses](https://github.com/OHDSI/FeatureExtraction/blob/main/inst/csv/PrespecAnalyses.csv), with `isDefault = FALSE`.

**Comment by anthonysena** [comment]
Closing as this has been merged into develop.
