### ISSUE TITLE
FeatureExtraction (as well as CohortDiagnostics) not compatible with newest versions of R?

### ISSUE THREAD

**Issue by tfalcs** [OHDSI/FeatureExtraction#171]
Hi @schuemie, when attempting to individually install FeatureExtraction and CohortDiagnostics for a OHDSI study package install, I encountered this error for the first time:  

Warning in install.packages :
  package ‘FeatureExtraction’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

I am using RStudio version 2022.02.03 Build 492 and R version 4.1.0 as well as version 4.2.1 (the latter downloaded after thinking my base R may have been the issue). However, after reading your post here:

https://github.com/OHDSI/DatabaseConnector/issues/27

and using its solution:

> devtools::install_github("ohdsi/CohortDiagnostics", args = "--no-multiarch")

both FeatureExtraction and CohortDiagnostics were installed. So I just wanted to document this little hiccup for my own remembrance as well for those who may encounter something similar in the future. A lot of my thinking about version incompatibilities is very uni-directional -- too old. But, as your solution points out, sometimes packages don't work so well on the newest versions of R.

**Comment by schuemie** [comment]
Neither FeatureExtraction nor CohortCohortDiagnostics are in CRAN, so these will always require `install_github()`. Did you try to use `install.packages()`?

**Comment by anthonysena** [comment]
Going to close this out due to inactivity but please let us know if you are still facing issues here @tfalcs.
