### ISSUE TITLE
Vignette 'CreatingCustomCovariateBuilders': duplicate cdmVersion arguments

### ISSUE THREAD

**Issue by ginberg** [OHDSI/FeatureExtraction#176]
In section Covariate construction function, the cdmVersion argument is defined twice, see https://github.com/OHDSI/FeatureExtraction/blob/main/vignettes/CreatingCustomCovariateBuilders.Rmd#L69-L72

**Comment by anthonysena** [comment]
Closing as this is merged into the develop branch and will be part of the v3.3.0 release.
