### ISSUE TITLE
Condition Group covariate bug

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/FeatureExtraction#18]
I found the following two errors in the code:

in GetCovariates.sql line 616:

  AND c1.@concept_class_id = 'Clinical finding'
  AND ca1.min_levels_of_separation = 1
  AND c1.concept_id NOT IN (select distinct descendant_concept_id from concept_ancestor where ancestor_concept_id = 441840 and max_levels_of_separation <= 2)

Should be (see bold)

  AND c1.@concept_class_id = **'Clinical Finding'**
  AND ca1.min_levels_of_separation = 1
  AND c1.concept_id NOT IN (select distinct descendant_concept_id from **@cdm_database_schema.concept_ancestor** where ancestor_concept_id = 441840 and max_levels_of_separation <= 2)

The first error is probably because of a vocab update? Maybe we should always cast to uppercase when doing string comparisons in SQL??

The second error is not a problem if cdm is the default schema only..

**Comment by schuemie** [comment]
Good catch!

Some SQL dialects (like SQL Server) are always case-insensitive when comparing strings, which is probably why we didn't notice it until now.

**Comment by schuemie** [comment]
Note that I've added some comments about this to the SqlRender vignette: https://github.com/OHDSI/SqlRender/commit/31a0ca453656434f25f7d1ab1f7d5ca24f13ad99

Now all we need is for people to actually read manuals ;-)
