### ISSUE TITLE
Fix minor typo in UsingFeatureExtraction.Rmd

### ISSUE THREAD

**Issue by rbcavanaugh** [OHDSI/FeatureExtraction#186]
Hi - Working through the very helpful UsingFeatureExtraction tutorial. 

I think line 436 should read

- `covariateId` identifies the covariate, and definitions of covariates can be found in the `covariateData$covariateRef` object

not

- `covariateId` identifies the covariate, and definitions of covariates can be found in the `cohortData$covariateRef` object. 

I can't find reference to a cohortData object in the vignette and `covariateData$covariateRef` appears to hold the referenced information. Apologies if this is wrong (and if so, please let me know where I Can find the cohortData object). Happy to create a pull request. Rob

**Comment by anthonysena** [comment]
Thanks @rbcavanaugh - I believe you are correct! If you could create a PR, I'll work to get that into the next release. Thank you!
