### ISSUE TITLE
procedure group

### ISSUE THREAD

**Issue by eldarallakhverdiiev** [OHDSI/FeatureExtraction#19]
Error at line 1278 (exclusion of codes for procedure grouping):
selected concept_id's (76094,67368, 46042, 40949, 31332, 28263, 24955, 18791, 13449, 12571, 10678, 10592, 9878, 9727, 9652, 9451, 9192, 8975, 8930, 8786, 8370, 8161, 7763, 7059, 6923, 6752, 6690, 6611, 6336, 6264, 6204, 6003, 5783) are not procedures at all. 
I expected to see there concepts like 
 4014829-'Consultation' or 4241075-'Injection'. 
     Also seems like you should collaborate with standardized vocabularies team to improve this part.
There are no proper relationships between different vocabularies for procedures. So, I'm not sure
all of procedures could be aggregated to SNOMED concepts

**Comment by cgreich** [comment]
@eldarallakhverdiiev:

Yes, these are not procedures. Where did you get them from?

**Comment by eldarallakhverdiiev** [comment]
https://github.com/OHDSI/FeatureExtraction/blob/master/inst/sql/sql_server/GetCovariates.sql
line 1278
