### ISSUE TITLE
Error when specifying only one temporal window in temporalCovariateSettings

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/FeatureExtraction#200]
I get the following error when specifying only one window in temporal covariate settings object

> Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
>   org.json.JSONException: JSONObject["temporalEndDays"] is not a JSONArray.

reproducible code

```

cohortDefinitionSet <-
  CohortGenerator::getCohortDefinitionSet(
    settingsFileName = "settings/CohortsToCreate.csv",
    jsonFolder = "cohorts",
    sqlFolder = "sql/sql_server",
    packageName = "SkeletonCohortDiagnosticsStudy",
    cohortFileNameValue = "cohortId"
  )

connectionDetails <- Eunomia::getEunomiaConnectionDetails()
connection <-
  DatabaseConnector::connect(connectionDetails = connectionDetails)


cohortTableNames = CohortGenerator::getCohortTableNames(cohortTable = 'cohort')

# Execution ----
## Create cohort tables on remote ----
CohortGenerator::createCohortTables(
  connectionDetails = connectionDetails,
  cohortDatabaseSchema = 'main',
  cohortTableNames = cohortTableNames,
  incremental = FALSE
)
## Generate cohort on remote ----
cohortGenerated <- CohortGenerator::generateCohortSet(
  connectionDetails = connectionDetails,
  cdmDatabaseSchema = 'main',
  cohortTableNames = cohortTableNames,
  cohortDefinitionSet = cohortDefinitionSet,
  cohortDatabaseSchema = 'main',
  incremental = FALSE
)

FeatureExtractionSettings <-
  FeatureExtraction::createTemporalCovariateSettings(
    useConditionEraGroupOverlap = TRUE,
    temporalStartDays = 0,
    temporalEndDays = 0
  )


featureExtractionOutput <-
  FeatureExtraction::getDbCovariateData(
    connection = connection,
    cdmDatabaseSchema = 'main',
    cohortDatabaseSchema = 'main',
    cohortTable = cohortTableNames$cohortTable,
    covariateSettings = FeatureExtractionCovariateSettings,
    aggregated = TRUE
  )

```

**Comment by gowthamrao** [comment]
same error if

FeatureExtractionSettings <-
  FeatureExtraction::createTemporalCovariateSettings(
    useConditionEraGroupOverlap = TRUE,
    temporalStartDays = c(0),
    temporalEndDays = c(0)
  )

**Comment by ginberg** [comment]
Actually @gowthamrao I can reproduce the error now. I got another error since the "FeatureExtractionCovariateSettings" param in getDbCovariateData does not exist (it does work with FeatureExtractionSettings).

If you are specifying the start and end days as a list, it does work. 
```
FeatureExtractionSettings <-
  FeatureExtraction::createTemporalCovariateSettings(
    useConditionEraGroupOverlap = TRUE,
    temporalStartDays = list(0),
    temporalEndDays = list(0)
  )
```
In the documentation it also states that these params should be a list, see
https://github.com/OHDSI/FeatureExtraction/blob/main/R/DefaultTemporalCovariateSettings.R#L114-L123
Does that work for you?

**Comment by anthonysena** [comment]
In discussion with @ginberg we should add a type check for the `temporalStartDays` and `temporalEndDays` to ensure the data type is a vector. It seems that when you specify `c(0)` it may not treat it as a proper vector and hence the error is raised.
