### ISSUE TITLE
getDbCohortBasedCovariatesData: BQ error

### ISSUE THREAD

**Issue by cyanover** [OHDSI/FeatureExtraction#208]
Great new feature type. Had to make two modifications to have it run on BigQuery: 
- in CohortBasedBinaryCovariates.sql, cast covariate_cohort_ref.cohort_id AS INT (originally, STRING)
- in GetCovariatesFromOtherCohorts.R, getDbCohortBasedCovariatesData (l141-146), add argument oracleTempSchema to   DatabaseConnector::renderTranslateExecuteSql call.

**Comment by anthonysena** [comment]
@cyanover - thanks for reporting these issues on Google BigQuery. Do you happen to have a branch with these changes for a pull request? If not we can follow your changes to include these fixes in the package.

**Comment by cyanover** [comment]
@anthonysena, thanks for looking into these issues. I haven't created a branch, hope my explanation is clear enough.
