### ISSUE TITLE
Order by clause in GetCovariates.sql

### ISSUE THREAD

**Issue by alondhe** [OHDSI/FeatureExtraction#22]
Hi,
In the GetCovariates.sql file, we have some insert statements that also include "order by" clauses: 
https://github.com/OHDSI/FeatureExtraction/blob/119ca34ade7316635b723680ee5c3f70235271bc/inst/sql/sql_server/GetCovariates.sql#L2245-L2281 

That's not valid in PDW (and I think in most other dialects?):
`The ORDER BY clause is invalid in views, CREATE TABLE AS SELECT, INSERT SELECT, inline functions, derived tables, subqueries, and common table expressions, unless TOP or FOR XML is also specified.)`

Does the ordering of these temp tables by source_code actually matter? Can the order by clauses be removed?

Thanks,
Ajit

**Comment by schuemie** [comment]
Oops, yes, I had already fixed that locally but forgot to push. I just did : cf2067e1e700f05ad13565ecc621233626821d66

I'm not sure why we didn't run into this before. Maybe it has to do with our recent PDW update?

**Comment by alondhe** [comment]
Oh okay, thank you!

Yep. I was looking through previous commits of the file, and those order by clauses were present and yet didn't blow up our many FeatureExtraction runs. I'll see if we can ascertain from Microsoft if the AU5 firmware caused the handling of order by to change.
