### ISSUE TITLE
SDM calculation fix

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/FeatureExtraction#223]
Following up on this based on a question I received. Per https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3472075/, for continuous variables it appears we should divide the SD on line 139:

https://github.com/OHDSI/FeatureExtraction/blob/6a7e90a76d28e74ab50604a97a6066e38a594d74/R/CompareCohorts.R#L134-L141

similar to what we are doing for binary covariates here on line 103:

https://github.com/OHDSI/FeatureExtraction/blob/6a7e90a76d28e74ab50604a97a6066e38a594d74/R/CompareCohorts.R#L96-L105

Tagging @schuemie for confirmation. I can then open an issue and get this patched.

_Originally posted by @anthonysena in https://github.com/OHDSI/FeatureExtraction/issues/120#issuecomment-1900757620_

**Comment by ginberg** [comment]
@anthonysena thanks for reporting, I will pick this up
