### ISSUE TITLE
Guidance for using condition occurrence group

### ISSUE THREAD

**Issue by solis9753** [OHDSI/FeatureExtraction#230]
Hi, 

I'd like to explore the possibility of using condition occurrence group, i.e. one covariate per condition rolled up to groups in the condition_occurrence table. It seems that the [SQL](https://github.com/OHDSI/FeatureExtraction/blob/main/inst/sql/sql_server/DomainConceptGroup.sql) is designed to handle the condition_occurrence table but I am not sure how to implement it using the package's features. 
Any guidance or clarification would be highly appreciated.

**Comment by ginberg** [comment]
hi @solis9753, you can create a covariateSettings object and set the parameter (i.e. "useConditionGroup<>" that you want. They are described in the documentation, see [code](https://github.com/OHDSI/FeatureExtraction/blob/main/R/DefaultCovariateSettings.R)
see the [vignette](https://ohdsi.github.io/FeatureExtraction/articles/UsingFeatureExtraction.html) on how to create code to use the package functionality

**Comment by solis9753** [comment]
Hi @ginberg, thanks for your response. 
I admit my introductory post might have been a bit confusing. While there exist parameters for condition group era (i.e "useConditionGroupEra<>"), there are no parameters to cover condition occurrence.  

Anhtony's [post](https://github.com/OHDSI/FeatureExtraction/pull/113#issuecomment-1948471769) on the equivalent case for drug exposure could work in my case (i.e use of cohort covariates), although it complicates the situation to an extend(having to create multiple cohorts). Another solution would be to create a custom covariate builder. 

Thanks. Feel free to close.
