### ISSUE TITLE
Extract Features between cohort_start and cohort_end

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/FeatureExtraction#253]
This issue proposes a new feature that can extract features between a cohort start and cohort end date.  

### Proposed Implementation

Leveraging DomainConcept.sql and DomainConceptGroup.sql introduce two new templates: DomainConceptDuring.sql and DomainConceptGroupDuring.sql that will not accept any time_interval or start/end days, but rather hard codes looking between target cohort start and end dates.   

Introduce analysis specifications in PrespectAnalyses.csv for each domain that we want to extract features for (Condition, ConditionGroup, Drug, DrugEra, DrugEraGroup, Procedure, Observation, Visit, etc).

**Comment by gowthamrao** [comment]
Similar to https://github.com/OHDSI/FeatureExtraction/issues/105

**Comment by chrisknoll** [comment]
We'll have to see if this issue is aligned with the intent of feature extraction.  It sounds like one perspective is feature extraction should only extract 'baseline covariates' at a prior-index time window.   This would be looking forward, and I'm not sure if that would step outside the box of FE's intent.  I would want to not introduce something that would work contrary to the intent of the library.
