### ISSUE TITLE
Update custom covariate builder vignette

### ISSUE THREAD

**Issue by schuemie** [OHDSI/FeatureExtraction#258]
At some point in time, the covariate builder function gained a new argument: `minCharacterizationMean`. Please update the [vignette](https://ohdsi.github.io/FeatureExtraction/articles/CreatingCustomCovariateBuilders.html) accordingly (now FeatureExtraction throws an error if the argument isn't present)

**Comment by alondhe** [comment]
Just ran into this :) 

So now, the builder function needs simply the parameter of minCharacterizationMean, right? Which you could default to 0?

**Comment by anthonysena** [comment]
Yes, that's right - add "minCharacterizationMean = 0" and you should be set. We'll get the vignette updated. Sorry for that!
