### ISSUE TITLE
Min characterization mean 

### ISSUE THREAD

**Issue by azimov** [OHDSI/FeatureExtraction#274]
This following occuring in CohortDiagnostics and causing unit tests to fail:

```
DBMS:
postgresql

Error:
org.postgresql.util.PSQLException: ERROR: column "average_value" does not exist
  Position: 580

SQL:
SELECT all_covariates.cohort_definition_id,
  all_covariates.covariate_id,
  all_covariates.time_id,
  all_covariates.sum_value,
  CAST(all_covariates.sum_value / (1.0 * total.total_count) AS NUMERIC) AS average_value
FROM (SELECT cohort_definition_id, covariate_id, sum_value, time_id FROM cov_1
) all_covariates
INNER JOIN (
SELECT cohort_definition_id, COUNT(*) AS total_count
FROM ohdsi.ct_76342172599075731 
WHERE cohort_definition_id IN (17720, 18345, 14907) GROUP BY cohort_definition_id
) total
  ON all_covariates.cohort_definition_id = total.cohort_definition_id WHERE average_value >= 0.001;

R version:
R version 4.4.0 (2024-04-24)

```

The problem is with the where statement `WHERE average_value >= 0.001;` (and removing the min characterization mean parameter fixes the problem).
Filtering on the value with name "AS average_value" will not work unless nested inside another subquery.

Instead the query should be:

```
SELECT all_covariates.cohort_definition_id,
  all_covariates.covariate_id,
  all_covariates.time_id,
  all_covariates.sum_value,
  CAST(all_covariates.sum_value / (1.0 * total.total_count) AS NUMERIC) AS average_value
FROM (SELECT cohort_definition_id, covariate_id, sum_value, time_id FROM cov_1
) all_covariates
INNER JOIN (
SELECT cohort_definition_id, COUNT(*) AS total_count
FROM ohdsi.ct_76342172599075731 
WHERE cohort_definition_id IN (17720, 18345, 14907) GROUP BY cohort_definition_id
) total
  ON all_covariates.cohort_definition_id = total.cohort_definition_id 

WHERE all_covariates.sum_value / (1.0 * total.total_count) >= 0.001;
```

Which appears to be set [here](https://github.com/OHDSI/FeatureExtraction/blob/b5bb15da2cb60126bec0f317fc813c3a9c067836/java/org/ohdsi/featureExtraction/FeatureExtraction.java#L747)

**Comment by anthonysena** [comment]
Sorry for this @azimov - tagging @ginberg to enlist some help. It appears that our unit tests are incomplete - we should add a non-zero value for the `minCharacterizationMean` so that we can properly test this across DB platforms. This should be done [here](https://github.com/OHDSI/FeatureExtraction/blob/main/tests/testthat/test-query-no-fail.R#L185-L309) and [here](https://github.com/OHDSI/FeatureExtraction/blob/main/tests/testthat/test-query-no-fail.R#L472-L523)
