### ISSUE TITLE
cohort_attribute

### ISSUE THREAD

**Issue by sgasmanjj** [OHDSI/FeatureExtraction#278]
Hello!

It seems that the cohort_attribute table no longer exists in the omop cdm. Is this functionality still available in the FeatureExtraction package? https://ohdsi.github.io/FeatureExtraction/articles/CreatingCovariatesUsingCohortAttributes.html

If so, is there another cdm table that should be used to store cohort attributes, or should an additional table be created (temp?) to house them?

Thank you!
Sarah

**Comment by anthonysena** [comment]
Hi Sarah - you can create the `cohort_attribute` table in your "work" schema (i.e. where you store your cohort tables). The tables and columns are described a bit [here](https://ohdsi.github.io/FeatureExtraction/articles/CreatingCovariatesUsingCohortAttributes.html#populating-the-cohort_attribute-and-attribute_definition-tables) in the vignette but let us know if you need any further details.

**Comment by sgasmanjj** [comment]
Thank you for clarifying! The wording here<https://ohdsi.github.io/FeatureExtraction/articles/CreatingCovariatesUsingCohortAttributes.html#overview> makes it sound like an existing table in the cdm, so I was a little confused! I appreciate the clarification.

From: Anthony Sena ***@***.***>
Sent: Friday, October 4, 2024 9:17 AM
To: OHDSI/FeatureExtraction ***@***.***>
Cc: Gasman, Sarah [JRDUS NON-J&J] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [OHDSI/FeatureExtraction] cohort_attribute (Issue #278)


Hi Sarah - you can create the cohort_attribute table in your "work" schema (i.e. where you store your cohort tables). The tables and columns are described a bit here<https://ohdsi.github.io/FeatureExtraction/articles/CreatingCovariatesUsingCohortAttributes.html#populating-the-cohort_attribute-and-attribute_definition-tables> in the vignette but let us know if you need any further details.
