### ISSUE TITLE
Error in MeasurementValue.sql

### ISSUE THREAD

**Issue by sgasmanjj** [OHDSI/FeatureExtraction#279]
Hello!

I believe there is a missing comma at the end of line 54 of the MeasurementValue.sql script. When I attempt to include UseMeasurementValue as a feature in CreateTemporalSequenceCovariateSettings, I get an error.

https://github.com/OHDSI/FeatureExtraction/blob/main/inst/sql/sql_server/MeasurementValue.sql#L54 

<img width="205" alt="image" src="https://github.com/user-attachments/assets/73efc2cc-27c1-4ee7-85af-41c32e19cab5">

Let me know if I can provide more information! Thank you!
Sarah

**Comment by ginberg** [comment]
@sgasmanjj you are right, thanks for reporting! I made a PR for it

**Comment by sgasmanjj** [comment]
Wonderful, thanks so much! Do you happen to have a timeline for when the change will go live? I'm hoping to include this covariate in a project that we'll start running the code for in ~2 weeks. But I can recreate this as a custom covariate if needed!

**Comment by ginberg** [comment]
@sgasmanjj a new release, including this change, is available on CRAN
