### ISSUE TITLE
FeatureExtraction 2 - Demographics - Is there a way to calculate distinct counts by subject_id?

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/FeatureExtraction#39]
Is there a way to calculate distinct counts by subject_id?

> A cohort is defined as the set of persons satisfying one or more inclusion criteria for a duration of time. One person may qualify for one cohort multiple times during non-overlapping time intervals. 

Cohort definition allows a subject_id to be present more than once in a cohort. Can we support something like COUNT(distinct subject_id) to calculate unique subjects?

**Example in DemographicsGender.sql**
When aggregate is chosen in FeatureExtraction for DemographicsGender, the current version performs COUNT(*). This will count the number of records, not number of unique subjects.

https://github.com/OHDSI/FeatureExtraction/blob/9f78454933e2710e99a886ab4a447b56d7cb9d11/inst/sql/sql_server/DemographicsGender.sql#L8

One option is to change `COUNT(*)` to `COUNT(subject_id)` by default, and create a sub_type for distinct `COUNT(distinct subject_id)`

**Comment by schuemie** [comment]
Could you help me: I'm having a hard time imagining a use case where this is appropriate. Cohort characterization is a clearly defined task, but you seem to want to characterize the population that is participating in a cohort. If that is the case, why not construct a new cohort that is specifically the population you wish to characterize? (For example, de-duping subjects by picking the first cohort entry per subject.)

**Comment by gowthamrao** [comment]
Thank you @schuemie . You are correct, one approach may be to construct a new cohort which is constructed using the first occurrence of the subject_id. 

Use case - we want to calculate a measure - **records per subject_id** for a defined cohort. This measure is an indicator of churn/stability of the population - is the population going in and out of the cohort. We need to look at the populations distribution of the churn. An extremely squewed distribution indicates that only a few people are churning a lot, while a uniform distribution indicates that everyone is uniformly churning. 

e.g. we may have a cohort where few subject_ids in the population churning 5 times, while vast majority are not churning. The subject_id that churned most is an outlier, that we may want to take out - during a sensitivity analysis of models sensitivity to the churn.
