### ISSUE TITLE
FeatureExtraction2 - wish list

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/FeatureExtraction#41]
@schuemie could we add the following to the PrespecAnalyses list?

**Comment by gowthamrao** [comment]
Visits
- number of visit_occurrence records
- number of visit_occurrence records by place_of_service_concept_id
e.g. number of visit_occurrence records by inpatient, outpatient, doctor's office, ambulatory surgical center.

- number of visit_occurrence records by condition_occurrence
e.g. number of visit_occurrence records with primary diagnosis of influenza. Number of visit_occurrence records with primary or secondary diagnosis of hypertension.

- number of visit_occurrence records by procedure_occurrence
e.g. Number of cardiac catheterization visits. Number of hip replacements at an ambulatory surgical center place of service.

- number of visit_occurrence records by condition_occurrence by place_of_service
e.g. number of visit_occurrence records with primary diagnosis of influenza in emergency room 

- number of visit_occurrence records by procedure_occurrence by condition_occurrence by place_of_service
e.g. number of visit_occurrence records with procedure of cardiac catheterization and primary diagnosis of myocardial infarction at an inpatient place of service

**Comment by gowthamrao** [comment]
**Visit_Occurrence length of stay**
- number of days of visit per person for a certain procedure/condition/place_of_service/provider specialty -- or any combination.

**Comment by schuemie** [comment]
Just trying to organize this in my head. Which ones of these are covered by the modifications to ConceptCount.sql you've proposed [here](https://github.com/OHDSI/FeatureExtraction/issues/33)?
