### ISSUE TITLE
Integer out of range error MeasurementValue.sql

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/FeatureExtraction#42]
On PostGresql we get an integer out of range error due to this line. 

https://github.com/OHDSI/FeatureExtraction/blob/b7c8cbc49975c13a0c43d3a7d1cb3f6ed960ca83/inst/sql/sql_server/MeasurementValue.sql#L6 

Do we need to multiply with 1000000?

**Comment by schuemie** [comment]
Yes, multiplying by 1000000 gives 3 free digits for the analysis ID and 3 free digits for the unit concept ID (which therefore can already become non-unique).

I guess we need to cast measurement_concept_id to BIGINT before multiplying.

(In fact, I think we need to cast all covariateIds to BIGINT)

**Comment by PRijnbeek** [comment]
Yes I see, you indeed need the extra digits here because of the additional unit_concept. 
Casting to BIGINT would work.

**Comment by schuemie** [comment]
Just pushed to [develop](https://github.com/OHDSI/FeatureExtraction/commit/9d58d36958e8122c079d6ce6c243b41bcbc4f178). @PRijnbeek : could you give this a try?

**Comment by PRijnbeek** [comment]
Yes this fixes the problem. Thanks

**Comment by schuemie** [comment]
Now in master
