### ISSUE TITLE
useDemographicsTimeInCohort error: Invalid column name 'cohort_end_date'

### ISSUE THREAD

**Issue by alondhe** [OHDSI/FeatureExtraction#44]
When using useDemographicsTimeInCohort = TRUE, I am getting a SQL error for 
`Invalid column name 'cohort_end_date'`.

Probably due to unavailability of the field in this select:
https://github.com/OHDSI/FeatureExtraction/blob/master/inst/sql/sql_server/DemographicsTime.sql#L43

**Comment by schuemie** [comment]
I'm sorry, I'm unable to reproduce that error. Are you sure your cohort table has a `cohort_end_date` field?

**Comment by alondhe** [comment]
Yep, my scratch cohort table for my T and C has the same structure as the CDM cohort:
cohort_definition_id, subject_id, cohort_start_date, cohort_end_date; and the O cohort is in the actual CDM cohort table.  

Interestingly, I've tested using the getDbCovariateData function directly rather than through CohortMethod, and it doesn't throw the error. I think perhaps CohortMethod isn't including cohort_end_date in the #cohort_person temp table?

**Comment by schuemie** [comment]
I've merged your pull request for CohortMethod, so I think this problem should be solved now.

However, I must warn that in general it is not a good idea to use information post-index date in your propensity or outcome model. In this case, the time in cohort (e.g. time on the drug) is most likely causally intertwined with the outcome itself.

**Comment by alondhe** [comment]
Thanks @schuemie! My mistake -- I thought the default setting was TRUE, so I included it in my analysis. But I see now you've defaulted it to FALSE. But, hey, at least the bug is gone :)
