### ISSUE TITLE
Number of ER visits

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/FeatureExtraction#51]
Please add a feature to allow for Long, Medium, Short term covariates for number of ER visits.

**Comment by gowthamrao** [comment]
Tying these issues together
https://github.com/OHDSI/FeatureExtraction/issues/49
https://github.com/OHDSI/FeatureExtraction/issues/50
https://github.com/OHDSI/FeatureExtraction/issues/51

You probably already know this @fdefalco but we created a WG http://forums.ohdsi.org/t/workgroup-for-cost-utilization-economic-services/3976

Utilization portion is essentially record-count (or number of ER visits, number of inpatient visits etc). Here are some[ table shells ](https://docs.google.com/spreadsheets/d/1On3Kzlq42EYBfmn2yp8LXQi_go_gth9XV9nSuEhJnjw/edit?usp=sharing)

**Comment by anthonysena** [comment]
Closed via 297c0f302d9d41e5f87ccbe226240f7465607ae5
