### ISSUE TITLE
table1.R bug

### ISSUE THREAD

**Issue by jreps** [OHDSI/FeatureExtraction#54]
I'm having an issue with https://github.com/OHDSI/FeatureExtraction/blob/master/R/Table1.R#L140 
There is only one continuous covariate, so the colnames() function fails as it is a vector.  I think converting it to a data.frame should fix the issue: tempCovariates <- as.data.frame(tempCovariates)

I just tried this in debug but then I also have another issue later on: Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 9, 11

**Comment by schuemie** [comment]
I think I [fixed it](https://github.com/OHDSI/FeatureExtraction/commit/740a8c6eaa667f4c5b2c481bb000e4f472d6d589). Could you install the lastest on master and try again?
