### ISSUE TITLE
Parallelization of tidyCovariateData()

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/FeatureExtraction#60]
Would it be possible to parallelize this function?

For very large data sets (>500000 by 50000 data table), and especially for temporal covariates with small time window, the function takes relatively long to compute. We have a powerful machine (56 threads and some 700 GB of memory) and it would be great to be able to scale to that.

**Comment by schuemie** [comment]
Yep, that is possible. Probably best to parallelize [this for-loop](https://github.com/OHDSI/FeatureExtraction/blob/master/R/Normalization.R#L137) using the clusterApply function in ParallelLogger. I don't have the time right now to work on it, but you're welcome to give it a shot.

**Comment by anthonysena** [comment]
@lhjohn - just cleaning up a bit here. Seems like this may have been addressed via #136? Let me know if you desire further optimization and we can continue to keep this open.
