### ISSUE TITLE
Current version doesn't work for observation, device, and measurement. 

### ISSUE THREAD

**Issue by chandryou** [OHDSI/FeatureExtraction#64]
Hello, @schuemie 

Current version doesn't work for observation, device, measurement, and indexes such as CHADS. 
When I included these terms, error occurred

`r in nchar(object, type = "char"):
invalid multibyte string, element 4`

I'm using CDM version 5.3 with SQL Server. Do you have any idea about why it doesn't work..?

**Comment by schuemie** [comment]
Could you provide your covariate settings, so I can try to reproduce this problem?  You're running SQL Server, right?

**Comment by schuemie** [comment]
I can't reproduce the error, and it is also not detected in [our unit tests](https://github.com/OHDSI/FeatureExtraction/blob/master/tests/testthat/test-query-no-fail.R#L90). I think there must be some discrepancy between the database structure and what FE is expecting. Could you run the following SQL on your database to retrieve the structure of the `observation` table?:

```sql
SELECT o.name Table_Name, c.name Column_Name, t.name DataType, c.Length, CASE WHEN c.isnullable=1 THEN   'Yes'   ELSE   'No'   END AS 'Nullable' 
FROM sysobjects o
INNER JOIN syscolumns c ON (o.id=c.id and o.type='U' and o.name not like 'dt%')
Inner Join systypes t ON (c.xtype=t.xtype) 
WHERE o.name = 'observation'
ORDER BY o.name, c.name 
```

Here's ours:

Table_Name | Column_Name | DataType | Length | Nullable
-- | -- | -- | -- | --
observation | observation_concept_id | bigint | 8 | No
observation | observation_date | date | 3 | No
observation | observation_id | bigint | 8 | No
observation | observation_source_concept_id | bigint | 8 | Yes
observation | observation_source_value | varchar | 250 | Yes
observation | observation_time | varchar | 10 | Yes
observation | observation_type_concept_id | bigint | 8 | No
observation | person_id | bigint | 8 | No
observation | provider_id | bigint | 8 | Yes
observation | qualifier_concept_id | bigint | 8 | Yes
observation | qualifier_source_value | varchar | 250 | Yes
observation | unit_concept_id | bigint | 8 | Yes
observation | unit_source_value | varchar | 250 | Yes
observation | value_as_concept_id | bigint | 8 | Yes
observation | value_as_number | float | 8 | Yes
observation | value_as_string | varchar | 500 | Yes
observation | visit_occurrence_id | bigint | 8 | Yes

**Comment by chandryou** [comment]
Yes, I think so. 
Because I'm working outside of our office, I'll run this code next week. 

By the way.. what is the observation_time?

**Comment by schuemie** [comment]
Ahem, yes, sorry, that was an old CDM

This is from a v5.2.0 databasee (which is the newest we appear to have):


Table_Name | Column_Name | DataType | Length | Nullable
-- | -- | -- | -- | --
observation | observation_concept_id | bigint | 8 | No
observation | observation_date | date | 3 | No
observation | observation_datetime | varchar | 10 | Yes
observation | observation_id | bigint | 8 | No
observation | observation_source_concept_id | bigint | 8 | Yes
observation | observation_source_value | varchar | 250 | Yes
observation | observation_type_concept_id | bigint | 8 | No
observation | person_id | bigint | 8 | No
observation | provider_id | bigint | 8 | Yes
observation | qualifier_concept_id | bigint | 8 | Yes
observation | qualifier_source_value | varchar | 250 | Yes
observation | unit_concept_id | bigint | 8 | Yes
observation | unit_source_value | varchar | 250 | Yes
observation | value_as_concept_id | bigint | 8 | Yes
observation | value_as_number | float | 8 | Yes
observation | value_as_string | varchar | 500 | Yes
observation | visit_detail_id | bigint | 8 | Yes
observation | visit_occurrence_id | bigint | 8 | Yes
