### ISSUE TITLE
issue with latest SqlRender

### ISSUE THREAD

**Issue by jreps** [OHDSI/FeatureExtraction#69]
in line 102 in GetCovariates.R the code:
sql <- SqlRender::translateSql(sql = sql,
                                 targetDialect = attr(connection, "dbms"),
                                 oracleTempSchema = oracleTempSchema)$sql

is causing issues in the PLP package with the new SqlRender as it returns:
Warning: 'SqlRender::translateSql' is deprecated.
Use 'translate' instead.
See help("Deprecated")

**Comment by schuemie** [comment]
Well, it's just a warning that you could ignore, but I'll release a new version shortly

**Comment by jreps** [comment]
Thanks.  For some reason the plp code was just stopping at this warning - I went into debug mode and the code just stopped at the warning point.  Then it started to go past the warning for about 5 models and then it stopped again.  I have no idea why the warning was causing issues randomly.  I think this was the issue Henrik was running into.
