### ISSUE TITLE
Aggregate covariates to get summary statistics

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/FeatureExtraction#7]
I am looking for a way to get Achilles-like summary data from the covariates produced by `getDbCovariateData()`. 
To show what I mean, I made a small script that aggregates the covariate data from two cohorts and counts the number of occurrences. See output in the table below.

My question is, can this already be done by any in-build functions of this package? Or do you have other suggestions to extract this information using OHDSI tools?

|  | covariateName | occurrences.cohort1 | occurrences.cohort2 |
| --- | --- | --: | --: |
| 1 | Age group: 35-39 | 3 | 1 |
| 2 | Age group: 40-44 | 2 | 8 |
| 3 | Age group: 45-49 | 9 | 45 |
| 4 | Age group: 50-54 | 13 | 50 |
| 5 | Age group: 55-59 | 37 | 55 |
| 6 | Age group: 60-64 | 107 | 98 |
| 7 | Age group: 65-69 | 486 | 234 |
| 8 | Age group: 70-74 | 3112 | 2031 |
| 9 | Age group: 80-84 | 4045 | 3451 |
| 10 | Age group: 85-89 | 501 | 1234 |
| 11 | Age group: 90-94 | 81 | 55 |
| 12 | Age group: 95-99 | 14 | 10 |
| 13 | Gender = MALE | 6167 | 9317 |
| 14 | 320128-Essential hypertension | 725 | 1743 |
| 15 | 4193704-Type 2 diabetes mellitus without complication | 252 | 313 |

Produced for each cohort by: 
`agg_counts <- aggregate( covariateValue ~ covariateId, FUN=length, data =  cov )`

**Comment by schuemie** [comment]
Hi @MaximMoinat ,

You may want to take a look at the [computeCovariateBalance function](https://github.com/OHDSI/CohortMethod/blob/master/R/PsFunctions.R#L876) in the [CohortMethod](https://github.com/OHDSI/CohortMethod) package, which does what you need and more.

Cheers,
Martijn

**Comment by MaximMoinat** [comment]
Thanks a lot for this hint. We have been using the computeCovariateBalance function already for the top 10 covariate plots. Was not aware that there was a lot more information available in the balance data frame (although it makes a lot of sense now). 
Thanks!

Side note: it says in the documentation that the population data frame only needs the rowId and treatment columns. However, I think the stratumId is required as well. At least, I got an error about this when giving the unstratified study population as input.

**Comment by schuemie** [comment]
Ah, yes, good point. The computeCovariateBalance is specifically designed to compute the effect of stratification or matching. 

I guess you'll need to pick and choose from the R code of that function to make a nice new function. Or just set stratumId to 1 for all for a not-so-nice solution ;-)

**Comment by schuemie** [comment]
Added a long time ago
