### ISSUE TITLE
The link for vignette of 'Creating custom covariate builders' in readMe file doesn't work

### ISSUE THREAD

**Issue by chandryou** [OHDSI/FeatureExtraction#70]
@schuemie 
The link for vignette of 'Creating custom covariate builders' in readMe file doesn't work, now.

**Comment by chandryou** [comment]
I can see the vignette, here http://ohdsi.github.io/FeatureExtraction/articles/CreatingCustomCovariateBuilders.html
@schuemie , could you change the link in the ReadMe, too?

**Comment by schuemie** [comment]
Thanks! Those links in the README file point to the PDF versions, which somehow got lost (probably due to devtools, which now has a new 'feature' of sometimes deleting vignette PDF files).

I also added the link to the documentation website to the README.
