### ISSUE TITLE
Integer overflow in rowId for large datasets

### ISSUE THREAD

**Issue by spfohl** [OHDSI/FeatureExtraction#74]
For large datasets with many features, extraction fails due to integer overflow in R. I cannot tell exactly when the error occurs, but I think it is likely at the stage of compiling the ffdf for export. I reran this extraction by extracting each covariate type as a separate job and was able to run each of them without error, which would indicate that the error arises in the aggregation step. I did some manual aggregation of the resulting features in Python, and found that the analysis produces 2637228647 rows, which I believe breaks the positive integer limit for a signed 32-bit integer, which I believe should be (2^31)/2 - 1.

I get the following message at stderr:
`Error: Error executing SQL:
missing value where TRUE/FALSE needed
An error report has been created at  <path>/errorReport.txt
In addition: Warning message:
In len + to : NAs produced by integer overflow`

and in errorReport.txt:
`DBMS:
postgresql

Error:
missing value where TRUE/FALSE needed

SQL:
SELECT *
FROM (
SELECT row_id, covariate_id, covariate_value FROM cov_1 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM cov_2 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM cov_3 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM cov_4 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM cov_5 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM cov_6 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM cov_7 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM cov_8 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM cov_9 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM cov_10 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM cov_11 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM cov_12 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM cov_13 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM cov_14
) all_covariates;`

**Comment by schuemie** [comment]
Note that the row_id column should be a unique value per cohort entry, so usually well within the 32-bit integer range.

But yes, the ff package has as limitation that it cannot contain more rows than can be stored in a 32-bit integer. In the past, when I ran into this problem, there usually was an obvious way to reduce the size. For example, maybe you're getting covariates for 100 cohorts at once, and you could do it per cohort instead? Or you don't really need all covariates, but just the subset needed for your prediction model?

If you could explain your use case a bit, perhaps there's an obvious way forward.

**Comment by spfohl** [comment]
Oh you're right that the issue isn't that rowId overflows, but rather just the total number of rows.

The use case here is to develop a prediction model for a large cohort of approximately 10 million patients in Optum. The features we are extracting are essentially just all of binary features prior to the index date without any time binning. Arguably, we could restrict the history available, partition the cohort, or just ask for fewer features, but the goal here is to just extract a reasonable approximation to "everything" for a large cohort.

Here's the covariate settings:
```
createCovariateSettings(useDemographicsGender = TRUE,
                                    useDemographicsAgeGroup = TRUE,
                                    useDemographicsRace = TRUE, 
                                    useDemographicsEthnicity = TRUE,
                                    useDemographicsIndexYear = TRUE, 
                                    useDemographicsIndexMonth = TRUE,
                                    useConditionOccurrenceAnyTimePrior = TRUE,
                                    useConditionGroupEraAnyTimePrior = TRUE,
                                    useDrugExposureAnyTimePrior = TRUE, 
                                    useDrugGroupEraAnyTimePrior = TRUE, 
                                    useProcedureOccurrenceAnyTimePrior = TRUE,
                                    useDeviceExposureAnyTimePrior = TRUE,
                                    useMeasurementAnyTimePrior = TRUE, 
                                    useObservationAnyTimePrior = TRUE, 
                                    longTermStartDays = -365,
                                    mediumTermStartDays = -180, 
                                    shortTermStartDays = -30, 
                                    endDays = -1, # Do not use data on prediction day
                                    includedCovariateConceptIds = c(), 
                                    addDescendantsToInclude = FALSE,
                                    excludedCovariateConceptIds = c(), 
                                    addDescendantsToExclude = FALSE,
                                    includedCovariateIds = c()
                                   )
```

The workaround I have at the moment involves separating the extraction into separate extractions by concept types (e.g. drugs, conditions, procedures, etc). To get around the ff issue, I convert the individual ff files to csv using write.csv.ffdf, and then use Dask in Python to convert the files to Apache Parquet and handle the rest of the processing.

**Comment by schuemie** [comment]
I'm afraid there isn't much I can do about the ff package right now. I do have on my to-do list to completely rewrite it, but that is more a long-term goal.

One question is whether you really need all 10 million patients to fit the model. I know @PRijnbeek has done some research showing there is little benefit adding more people above some threshold (although I don't remember what number that is). I usually sample down to 250k when fitting a model.

**Comment by PRijnbeek** [comment]
Indeed we are writing up a paper on this topic, @lhjohn  is leading this. The threshold is dependent on the prevalence of the disease. Normally a couple of thousand people with the outcome seems to work well and adding more patients is only adding computational burden.

See also for example this [poster](http://www.ohdsi.org/web/wiki/lib/exe/fetch.php?media=resources:rijnbeek_learningcurves.pdf)

**Comment by spfohl** [comment]
Thanks @schuemie and @PRijnbeek. I agree that for prediction the marginal value of additional patients should drop off pretty quickly for some threshold far upstream of 10 million patients. 
I can envision some other use cases where we may need to extract large amounts of unlabeled data for some non-standard learning objectives, in which case there may be value in breaking the 32 bit limit. 

For now, I don't think it's worth re-engineering the whole package for this use case, but it's probably worth revisiting at some point.

**Comment by schuemie** [comment]
This issue should be resolved soon (next week) when we replace ff with Andromeda.
