### ISSUE TITLE
numeric custom covariates showing up in covariateData$covariates, should't it be covariateData$covariatesContinuous?

### ISSUE THREAD

**Issue by Sigfried** [OHDSI/FeatureExtraction#79]
As described here: https://github.com/Sigfried/HivDescriptive/issues/3, a custom covariate is disappearing from the result of aggregateCovariates. With LengthOfObservation (copied from the documentation), the values show up in covariates, not covariatesContinuous, but then they don't get included in aggregateCovariates ([lines 40 and 43](https://github.com/OHDSI/FeatureExtraction/blob/master/R/Aggregation.R#L40)) because the covariate it contains `N` in `covariateData$analysisRef$isBinary`.

Is this a bug or something I'm doing wrong?

**Comment by Sigfried** [comment]
Tried switching from running `aggregateCovariates()` to setting `aggregate = TRUE` for `getDbCovariateData()` and now I get an error message:

    Error in (function (connection, oracleTempSchema = NULL, cdmDatabaseSchema,  : 
      Aggregation not implemented for covariates from cohort attributes. 

So, I guess the only possible bug here is not seeing that error message with the `aggregateCovariates` function. Otherwise it's a feature request, and maybe I should figure out how to implement the feature.

**Comment by schuemie** [comment]
Hi @Sigfried !They're two unrelated issues:

The first issue is my bad: I used different values for the `analysisId` in the `covariateRef` and `analysisRef` objects, causing the aggregation to fail. I have now fixed this in the develop branch. I also added some more options to the `createCohortAttrCovariateSettings` to specify how the variable should be aggregated. Could you give this a try?

The second issue is because I haven't implemented the aggregation using SQL for these type of covariates.

**Comment by Sigfried** [comment]
Thanks, Martijn (@schuemie)!

I'm still a bit new to R coding, so, just to make sure, I just reinstalled FeatureExtraction like this:

    devtools::install_git('https://github.com/OHDSI/FeatureExtraction', ref = 'develop'

Let me know if that's wrong.

Now, as you mentioned, setting `aggregated = TRUE` in `getDbCovariateData` doesn't work (not implemented), but that `aggregateCovariates` function seems to be working.

I was surprised to see the covariate appear in both `covariateData$covariates` and `covariateData$covariatesContinuous`, but both seem to be correct (and not redundant):

```
Browse[2]> aggcovariates$covariates %>% ff::as.ram() %>% filter(covariateId == 1)
  covariateId sumValue averageValue
1           1    18014     461.8974

Browse[2]> aggcovariates$covariatesContinuous %>% ff::as.ram() %>%  filter(covariateId == 1)
  covariateId countValue minValue maxValue averageValue standardDeviation medianValue p10Value p25Value p75Value p90Value
1           1         39        0     1063     461.8974          263.6189         415      147      258      673      906

Browse[2]> aggcovariates$covariateRef %>% ff::as.ram() %>% filter(covariateId == 1)
  covariateId         covariateName analysisId conceptId
1           1 Length of observation          1         0
```
So all's good for now. Thanks!
