### ISSUE TITLE
Translation KR

### ISSUE THREAD

**Issue by Cafemug** [OHDSI/FeatureExtraction#80]
I have translated vignette. I think this is not completely so I will have  to  upgrade continuously

In first, I write on Notion

here are Translation Links

Using FeatureExtraction : 
[Using_FeatureExtraction.pdf](https://github.com/OHDSI/FeatureExtraction/files/3409014/Using_FeatureExtraction.pdf)

Creating custom covariate builders :
[Creating_custom_covariate_builders.pdf](https://github.com/OHDSI/FeatureExtraction/files/3409015/Creating_custom_covariate_builders.pdf)

I would like to do it more perfectly and try REDEME translation if I allow translation.

**Comment by chandryou** [comment]
@Cafemug Awesome! But the links are not accessible for me. How can I access those links?

**Comment by Cafemug** [comment]
> @Cafemug Awesome! But the links are not accessible for me. How can I access those links?

I change link to pdf file and `Creating covariates using cohort attributes` is removed because the translation is in progress.  And nowadays I try to transform FeatureExtraction  using Python  so I  think  I try to learn domain knowledge so In future I can translate better.

so i think this translation is not good, I want you to take a good response at it. 

Thanks

**Comment by chandryou** [comment]
Again, this is awesome! I'll review this on this weekend!

**Comment by Cafemug** [comment]
> Another option is publishing this as an appendix in the [Korean Book of OHDSI](https://github.com/ohdsi-korea/TheBookOfOhdsiKorea).
> Recently, I've got detailed instruction for OHDSI and ATLAS from Korean Ilsan hospital, which will be added to this book.

Oh, `Korean Book of OHDSI is good` ,I have known a bit by looking at the database using synpuf data in  developer Internship. If it is possible I want to participate in `Korean book of OHDSI` translation too. Is it possible?

**Comment by schuemie** [comment]
I'm happy to add these vignettes to the package, but preferably using the standard R vignette mechanism. Do you have these as Rmd files?

**Comment by Cafemug** [comment]
> I'm happy to add these vignettes to the package, but preferably using the standard R vignette mechanism. Do you have these as Rmd files?

Do you mean Markdown file?

Using FeatureExtraction :
[Using FeatureExtraction.zip](https://github.com/OHDSI/FeatureExtraction/files/3409450/Using.FeatureExtraction.zip)

Creating custom covariate builders :
[Creating custom covariate builders.zip](https://github.com/OHDSI/FeatureExtraction/files/3409451/Creating.custom.covariate.builders.zip)

Is this right?

**Comment by schuemie** [comment]
Close! That's markdown, and I need rmarkdown. I converted one of your documents [here](https://github.com/OHDSI/FeatureExtraction/blob/develop/vignettes/UsingFeatureExtractionKorean.Rmd). 

It renders fine to HTML:
![Capture](https://user-images.githubusercontent.com/6713328/61522407-9821dc80-aa12-11e9-9046-5c51913ec08d.PNG)

But rendering to PDF (e.g. using [this command](https://github.com/OHDSI/FeatureExtraction/blob/develop/extras/PackageMaintenance.R#L46)) throws this error message:
```
! Package inputenc Error: Unicode character ì„œ (U+C11C)
(inputenc)                not set up for use with LaTeX.
```
You wouldn't happen to know how to configure pandoc to play nice with Korean characters?

**Comment by Cafemug** [comment]
@schuemie 
I can't found convert Markdown to Rmarkdown

It is the my original translation. I write on Notion, so i attach link too

Using FeatureExtraction : https://www.notion.so/cafemug/Using-FeatureExtraction-1a82072c880c448caaacee4c4487cdaa
Creating custom covariate builders : https://www.notion.so/cafemug/Creating-custom-covariate-builders-8521b37997164bea9f06e2eb0296532a

i would hope so that you success to try to convert by using this.

but if you convert fail, i rewrite translation Rmd ver

**Comment by schuemie** [comment]
That's ok, I got it working. I was able to generate the PDF for [Using FeatureExtraction](https://github.com/OHDSI/FeatureExtraction/blob/develop/inst/doc/CreatingCustomCovariateBuildersKorean.pdf) and [Creating custom covariates](https://github.com/OHDSI/FeatureExtraction/blob/develop/inst/doc/CreatingCustomCovariateBuildersKorean.pdf). The HTML versions will be visible once I merge from develop to master.

In the future, please make textual changes in these files:

https://github.com/OHDSI/FeatureExtraction/blob/develop/vignettes/UsingFeatureExtractionKorean.Rmd

https://github.com/OHDSI/FeatureExtraction/blob/develop/vignettes/CreatingCustomCovariateBuildersKorean.Rmd

From there I can automatically regenerate the PDFs and HTML.

**Comment by Cafemug** [comment]
@schuemie  
oh thanks. so In future  if I  would modify translation and add another vignettes translation, would i try pull-request?

**Comment by schuemie** [comment]
Yes, please make changes using a pull-request.
