### ISSUE TITLE
Spark: Inserts with fewer columns than the table has

### ISSUE THREAD

**Issue by alondhe** [OHDSI/FeatureExtraction#82]
In Spark, if you run an insert statement with a column list, as in here:
https://github.com/OHDSI/FeatureExtraction/blob/master/inst/sql/sql_server/DomainConcept.sql#L53

It will fail for because we have a mismatched set of columns between the source and target (4 fields of data to be inserted into 5 columns).

I am adding the missing fields where appropriate. In the above example, I'll just add analysis_name to the column list and then throw a NULL value in for it in the select. I'll be adding these changes in the develop branch.

**Comment by alondhe** [comment]
Never mind, will try to handle in SqlRender

**Comment by schuemie** [comment]
Hmmm, in this case I think this is actually a bug in FE. `analysis_name` is a field of `#cov_ref` as defined [here](https://github.com/OHDSI/FeatureExtraction/blob/master/inst/sql/sql_server/CreateCovAnalysisRefTables.sql#L11), but we don't insert into it, and we don't extract the data, as seen [here](https://github.com/OHDSI/FeatureExtraction/blob/master/java/org/ohdsi/featureExtraction/FeatureExtraction.java#L473). Also, it would be redundant with the [analysis_ref table](https://github.com/OHDSI/FeatureExtraction/blob/master/inst/sql/sql_server/CreateCovAnalysisRefTables.sql#L15). 

I'll remove it from the definition.
