### ISSUE TITLE
ability to pick redundant concept

### ISSUE THREAD

**Issue by jreps** [OHDSI/FeatureExtraction#86]
The package currently automatically removes redundant covariates (e.g., only male or female gender will be used).  It would be useful to be able to pick the covariate that is removed.  For example:

useDemographicsGender = T,
excludedCovariateConceptIds = c(8532)

would give you male as a covariate

**Comment by schuemie** [comment]
Removal of redundant covariates isn't done until you call [`tidyCovariateData`](https://github.com/OHDSI/FeatureExtraction/blob/master/R/Normalization.R#L71), so you could remove the variable you don't want before that call, for example by using [`excludeCovariateConceptIds`](https://github.com/OHDSI/FeatureExtraction/blob/master/R/DefaultCovariateSettings.R#L367).

If your goal is to recreate the same set of features used in a model fitted elsewhere you should use [`includeCovariateIds`](https://github.com/OHDSI/FeatureExtraction/blob/master/R/DefaultCovariateSettings.R#L371).

**Comment by jreps** [comment]
That's what I thought, so I set:

useDemographicsGender = T,
excludedCovariateConceptIds = c(8532)

expecting male gender to be there (as I remove female) but there was no gender in the data.

**Comment by jreps** [comment]
Oh wait, I picked a random cohort in atlas that didn't mention in the title that it's 3rd complex inclusions criteria includes female only - so the solution was correct, but the cohort made it impossible to have male!
