### ISSUE TITLE
Que on creating custom covariates function 

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/FeatureExtraction#89]
Hello @schuemie ,

I was going through the Feature Extraction Manual and [http://ohdsi.github.io/FeatureExtraction/articles/UsingFeatureExtraction.html#creating-a-set-of-custom-covariates](doc) and have few question on this.

1) What does `DetailedSettings` do?

2) When (I mean in which scenarios) do we have to convert **PrespecSettings to DetailedSettings**?

![image](https://user-images.githubusercontent.com/30723825/78030322-7b58e980-7394-11ea-9148-83e9c955794d.png)

3) Do we get to see the Domain sql files?

![image](https://user-images.githubusercontent.com/30723825/78030420-a3e0e380-7394-11ea-848f-e36ee29242b8.png)

4) I understand that Feature Extraction package can be used to create `custom covariates`  but may I kindly check with you on what is the difference between `custom covariates`  and `detailed settings` and why do we need to generate detailed settings?

5) I see that in the doc we have the below example 

```
analysisDetails <- createAnalysisDetails(analysisId = 1,
                                         sqlFileName = "DemographicsGender.sql",
                                         parameters = list(analysisId = 1,
                                                           analysisName = "Gender",
                                                           domainId = "Demographics"),
                                         includedCovariateConceptIds = c(),
                                         addDescendantsToInclude = FALSE,
                                         excludedCovariateConceptIds = c(),
                                         addDescendantsToExclude = FALSE,
                                         includedCovariateIds = c())
```
From where do we get this sql file (`DemographicsGender.sql`)?, how can I view this SQL file?

**Comment by schuemie** [comment]
1. DetailedSettings allows you to use the existing SQL files, but call them with your own parameters. For example, you could create analysis with different start and end dates, and combine them into one set of analysis settings.

2. This is only for advanced users. And even for advanced users I haven't come across a valid use case.

3. They're embedded in the package: https://github.com/OHDSI/FeatureExtraction/tree/master/inst/sql/sql_server

4. Custom covariates provide much more freedom. For example, for custom covariates you are allowed to use your own SQL. The detailed settings only allow you to use the existing SQL files.

5. https://github.com/OHDSI/FeatureExtraction/blob/master/inst/sql/sql_server/DemographicsGender.sql
